server:
  port: 8080

spring:
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**

queue:
  movie:
    name: MovieQueue

management:
  endpoints:
    web:
      exposure:
        include: *
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway
